# Datasource is autoconfigured by Spring Boot Docker Compose support from `compose.yaml`.
# See **Service Connections** in https://docs.spring.io/spring-boot/reference/features/dev-services.html
# This is also the reason that the datasource is in a separate section in `application.yml`.

logging:
  level:
    uk.gov.justice.laadata.providers: DEBUG
