---
# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    groups:
      gradle-updates:
        exclude-patterns:
          - "uk.gov.justice.laa.providerdata.*"
      internal-packages:
        patterns:
          - "uk.gov.justice.laa.providerdata.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "**"
