{{/*
service.yaml
Creates a Kubernetes Service to expose the application pods.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider-data-service.fullname" . }}
  labels:
    {{- include "provider-data-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "provider-data-service.selectorLabels" . | nindent 4 }}
