# values-uat.yaml
# UAT environment override values for the chart.

target:
  environment: uat

prometheus:
  metricsQualifier: "pds-uat"

# Configuration for rate limiting.
rateLimit:
  rps: "100"   # requests per second
  rpm: "6000"  # requests per minute
  burst: "1"   # burst size, Very strict - minimal tolerance for traffic spikes

ingressInternal:
  enabled: false
  hosts:
    - host: "laa-provider-data-platform-uat.internal-non-prod.cloud-platform.service.justice.gov.uk"

ingress:
  enabled: false
  hosts:
    - host: "laa-provider-data-platform-uat.apps.cloud-platform.service.justice.gov.uk"
  tls:
    - hosts:
        - "laa-provider-data-platform-uat.apps.cloud-platform.service.justice.gov.uk"

ingressShared:
  enabled: false
  hosts:
    - host: "laa-provider-data-platform-uat.apps.live.cloud-platform.service.justice.gov.uk"
